### ISSUE TITLE
Timer loopt niet door wanneer app in background is

### ISSUE THREAD

**Issue by TomDoes** [TomDoes/Kooktijden_iOS#22]
Als je een timer start en naar het home screen gaat pauzeert de timer, dit werkte eerst wel dus bug!!

Misschien ook even testen of dit op simulator anders is

**Comment by TomDoes** [comment]
Dit werkt wel goed op de simulator...

**Comment by TomDoes** [comment]
Dit is wel een kut probleempje.. want de timer pauzeert en gaat pas later verder. We moeten of er voor zorgen dat de timer op de achtergrond blijft lopen, maar dan is de kans er dat als je een app opent die veel geheugen vraagt dat je timer gekilled wordt. Of we moeten via notifications zorgen dat ze op een bepaalde tijdstip vuren en dat we opslaan hoelaat de app naar achtergrond is gegaan en dat wanneer je terugkomt en de timer is nog niet afgelopen dat uitrekenen hoeveel tijd er verlopen is.

Waarschijnlijk is dit op te lossen door notifications te laten vuren op een bepaald tijdstip als de app naar de achtergrond verdwijnt. Dit zorgt er voor dat er op een bepaald tijdstip  (kun je uitrekenen met hoeveel tijd er nog op de timer zit) een notificatie wordt gevuurd ipv dat de timer op de achtergrond door hoeft te lopen. 

Zie het scheduling gedeelte hieronder

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW1


Jij nog ideeen @harmbrugge ?

**Comment by frankdoesburg** [comment]
Bestaat er in iOS niet iets vergelijkbaars met de Android Service klasse?

**Comment by TomDoes** [comment]
@harmbrugge 
Idee:

Situatie 1 app gaat naar achtergrond en gebruiker keert terug voordat de timer is afgelopen
1. Sla resterende tijd op timestamp wanneer timer afloopt op in user defaults -> Deze methode wordt in de applicationDidEnterBackground van appdelegate.swift aangeroepen.

bv timer.saveTimers()

2.  Wanneer de app weer naar de voorgrond komt wordt automatisch de applicationWillEnterForeground van de appdelegate.swift aangeroepen daarin kunnen we dan een functie timer.restoretimers oid aanroepen, die set alle timers opnieuw met de resterende tijd en geeft meldingen voor de timers die ondertussen zijn afgelopen

**Comment by TomDoes** [comment]
@harmbrugge 

Idee 2:

Is het op ios ook mogelijk om een timer in het notificationcenter te laten lopen? Dus dat je de timer ziet aflopen? als je van boven naar beneden swiped?

**Comment by harmbrugge** [comment]
Functionerende timer app:
https://github.com/ShinobiControls/iOS8-day-by-day/tree/master/25-notification-actions/NotifyTimely/NotifyTimely
